import 'package:hive_flutter/hive_flutter.dart';
import 'models/child_profile.dart';
import 'models/episode_progress.dart';
import 'models/parent_settings.dart';
import 'models/subscription_state.dart';

/// Initialise Hive and open all boxes.
/// Call once in main() before runApp().
class HiveStorageService {
  static const _profileBox      = 'child_profiles';
  static const _progressBox     = 'episode_progress';
  static const _settingsBox     = 'parent_settings';
  static const _subscriptionBox = 'subscription_state';

  static Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters — generated by build_runner
    if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(ChildProfileAdapter());
    if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(EpisodeProgressAdapter());
    if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(ParentSettingsAdapter());
    if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(SubscriptionStateAdapter());

    await Future.wait([
      Hive.openBox<ChildProfile>(_profileBox),
      Hive.openBox<EpisodeProgress>(_progressBox),
      Hive.openBox<ParentSettings>(_settingsBox),
      Hive.openBox<SubscriptionState>(_subscriptionBox),
    ]);
  }

  // ── Child profile ──────────────────────────────────────────────────────────

  Box<ChildProfile> get _profiles => Hive.box(_profileBox);

  ChildProfile? getProfile() => _profiles.get('current');

  Future<void> saveProfile(ChildProfile profile) =>
      _profiles.put('current', profile);

  // ── Episode progress ───────────────────────────────────────────────────────

  Box<EpisodeProgress> get _progress => Hive.box(_progressBox);

  EpisodeProgress? getProgress(String episodeId) => _progress.get(episodeId);

  Future<void> saveProgress(EpisodeProgress progress) =>
      _progress.put(progress.episodeId, progress);

  List<EpisodeProgress> allProgress() => _progress.values.toList();

  // ── Parent settings ────────────────────────────────────────────────────────

  Box<ParentSettings> get _settings => Hive.box(_settingsBox);

  ParentSettings getSettings() =>
      _settings.get('settings') ?? const ParentSettings();

  Future<void> saveSettings(ParentSettings settings) =>
      _settings.put('settings', settings);

  // ── Subscription state ─────────────────────────────────────────────────────

  Box<SubscriptionState> get _sub => Hive.box(_subscriptionBox);

  SubscriptionState getSubscription() =>
      _sub.get('sub') ?? const SubscriptionState();

  Future<void> saveSubscription(SubscriptionState sub) =>
      _sub.put('sub', sub);
}
